### ISSUE TITLE
ProcessCreateState and ProcessDeleteState should be simplified

### ISSUE THREAD

**Issue by MarcelMue** [giantswarm/endpoint-operator#12]
- [x] Both functions should receive a k8s `Endpoint` (not build the k8s object)
- [x] Operatorkit has to be updated to separate the true `Delete`/`Create` from the `Update` happening right now
- [x] Unit tests should be refactored to properly enforce the computation separation
- [x] Use properly typed return values instead of `interface{}` in `new*Change` functions

See https://github.com/giantswarm/endpoint-operator/pull/8#discussion_r148472628 for discussion.

**Comment by xh3b4sd** [comment]
@MarcelMue did you actually find time to work on this? The issue gets quite old and it would be nice to get rid of it (by fixing it).

**Comment by MarcelMue** [comment]
This is my top priority for the upcoming week.

**Comment by xh3b4sd** [comment]
How far are we with this? Top priority since 16 days.

**Comment by MarcelMue** [comment]
Closing here in favor of more fine grained issues.
