### ISSUE TITLE
make proper use of labels and annotations

### ISSUE THREAD

**Issue by xh3b4sd** [giantswarm/endpoint-operator#15]
There was a discussion going on towards the usage of annotations and labels to be able to filter pods within the scope of an informer and to be able to work with component specific information. See the result of the discussion.

> Ok so when you want to filter you should use labels and when you want to work with component specific state you should use annotations. In the case of the endpoint-operator we need to use both then.

- [ ] We should add a label to our KVM guest cluster pods to be able to only select the desired ones when using an informer to get event updates for them. This can be done for all pods in the kvm-operator. 
- [x] We should still use annotations for the IPs being found and added to the pods. The endpoint-updater looks for VM IPs and sets the value to the annotation. The endpoint-operator still reads annotations. This is already done and does not need to change.

**Comment by kopiczko** [comment]
When creating labels or annotations let's please prefix them.

I propose following scheme: `REPO.giantswarm.io/PARAM=VAL`. For `kvm-operator` the prefix would be `kvm-operator.giantswarm.io/`.

**Comment by xh3b4sd** [comment]
IMO this is rather a never ending story because of a lot of places we cannot just change right now. I would just close this issue to not pollute the backlog with something we constantly work on anyway. We documented how we want to structure labels here: https://github.com/giantswarm/fmt/blob/e0941cf8365eba93fb349bbc612983ff76c8647c/kubernetes/annotations_and_labels.md.
